version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data/db
    restart: always

  mongo:
    container_name: mongo
    image: mongo:4.4.1-bionic
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    restart: always
